### PR TITLE
Adds support to write custom tags to output file

### PR DESCRIPTION
**Pull request by crra**
Changes:
- adds the option '--set-meta' that takes a simple list of key/value pairs
- informs the user if the defined tag is not well-known according to the spec
- updates examples
- introduces go modules

Debatable:
- Adds a dependency to the  3rd party library [id3v2](github.com/bogem/id3v2) (MIT licensed)

### CODE REVIEW

**Comment by crra** [comment]
Sorry for the whitespace noise, gofmt was applied automatically by my IDE.

**Comment by dmulholl** [comment]
Hi Manuel, this looks great but to be honest this tool already has more features than I intended initially and I don't want to add any extra complexity to it. 

You're very welcome to fork it though and use it as a base for something more fully-featured - let me know if you do and I'll add a link to the readme.

**Comment by crra** [comment]
Understood. No problem, just discard the pull-request.

**Comment by crra** [comment]
Hello Darren,

I've created a new project: https://github.com/crra/mp3binder

**Comment by dmulholl** [comment]
That's fantastic. I've just added a link to the readme. There's definitely plenty of demand for a command line tool with more features than mp3cat - best of luck with it!

**Pull request closed without merging**
